### ISSUE TITLE
Add tab to visualize RDF as a graph

### ISSUE THREAD

**Issue by marioscrock** [cefriel/rapid-triples#3]
Use https://github.com/zazuko/graph-explorer or similar to visualize the RDF generated

**Comment by domme1908** [comment]
Due to the unforeseen complexity of integrating https://github.com/zazuko/graph-explorer into the current kcong-codebase we will not pursue this issue further for the time being. The work done will be kept on the branch [3-add-tab-to-visualize-rdf-as-a-graph](https://github.com/cefriel/rdform/tree/3-add-tab-to-visualize-rdf-as-a-graph). 
@marioscrock I will close this issue for now.
